### ISSUE TITLE
incorrect files location?

### ISSUE THREAD

**Issue by torvista** [Zen4All-nl/Zen-Cart-Structured-Data-using-Json#1]
Hi,
on first check it appears you have the jscripts for the index page in
/modules/index/
instead of
/pages/index/
so they do not get used/loaded on the index page.
And, as far as I understand only one of these three jscript files should be used, as applicable to the site content.
So maybe all three should require _manual_ enabling: I prefixed them with "hidden_..."

**Comment by Zen4All** [comment]
You are absolutely right about the file location.  Will fix that in a minute

**Comment by Zen4All** [comment]
The scrips are optional, so if you do not need/want one you can remove it from your server.
For a future release I am going to add some Database configs to make configuring easier. But that will take some time

**Comment by torvista** [comment]
...on further reading it appears the index jscript should really be included on every page so should be in the template jscript.
http://webmasters.stackexchange.com/a/54703

**Comment by Zen4All** [comment]
I can't remember the exact page right now, but it was a google page that told me these three only need to be loaded on one page. But I am pretty sure it can not hurt to load them site-wide.
You can move the 3 files to 'includes/templates/YOUR_TEMLATE/jscript' is you like. I'll do some more research on the issue tomorrow
